// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mandiri_test.Services.TransAPI.Data;

#nullable disable

namespace mandiri_test.Services.TransAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240521105317_MandiriTestTransDB")]
    partial class MandiriTestTransDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mandiri_test.Services.TransAPI.Models.Pinjam", b =>
                {
                    b.Property<int>("IdTrans")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTrans"));

                    b.Property<DateTime?>("TanggalPinjam")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTrans");

                    b.ToTable("Pinjam");
                });

            modelBuilder.Entity("mandiri_test.Services.TransAPI.Models.PinjamDetail", b =>
                {
                    b.Property<int>("IdTransDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransDetail"));

                    b.Property<int>("IdBuku")
                        .HasColumnType("int");

                    b.Property<int>("IdTrans")
                        .HasColumnType("int");

                    b.HasKey("IdTransDetail");

                    b.HasIndex("IdTrans");

                    b.ToTable("PinjamDetail");
                });

            modelBuilder.Entity("mandiri_test.Services.TransAPI.Models.PinjamDetail", b =>
                {
                    b.HasOne("mandiri_test.Services.TransAPI.Models.Pinjam", "Pinjam")
                        .WithMany("PinjamDetails")
                        .HasForeignKey("IdTrans")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pinjam");
                });

            modelBuilder.Entity("mandiri_test.Services.TransAPI.Models.Pinjam", b =>
                {
                    b.Navigation("PinjamDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
