// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mandiri_test.Services.BukuAPI.Data;

#nullable disable

namespace mandiri_test.Services.BukuAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mandiri_test.Services.BukuAPI.Models.Buku", b =>
                {
                    b.Property<int>("IdBuku")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBuku"));

                    b.Property<double>("Harga")
                        .HasColumnType("float");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JumlahBuku")
                        .HasColumnType("int");

                    b.Property<string>("Penerbit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pengarang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TahunTerbit")
                        .HasColumnType("int");

                    b.HasKey("IdBuku");

                    b.ToTable("Buku_");

                    b.HasData(
                        new
                        {
                            IdBuku = 1,
                            Harga = 29000.0,
                            Judul = "Anilsa Keuangan",
                            JumlahBuku = 20,
                            Penerbit = "Media 1",
                            Pengarang = "Tobby",
                            TahunTerbit = 1999
                        },
                        new
                        {
                            IdBuku = 2,
                            Harga = 35000.0,
                            Judul = "Keuangan",
                            JumlahBuku = 10,
                            Penerbit = "Media 1",
                            Pengarang = "P Tobby",
                            TahunTerbit = 1999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
